### ISSUE TITLE
Steam friends language

### ISSUE THREAD

**Issue by vitalii0133** [TiberiumFusion/FixedSteamFriendsUI#3]
Is it possible to somehow change the language of Steam friends from English to another after applying the patch?

**Comment by TiberiumFusion** [comment]
It is not possible in the current version.

In my rush to get the patch finished and released as soon as possible, I skipped testing in other languages. So v1.0.0 is unfortunately stuck in English.

I will investigate getting the other languages working the day after tomorrow when I have some more free time. And if all goes well, the next update to the patch will have this fixed.

**Comment by TiberiumFusion** [comment]
@vitalii0133 
Version 1.1.0 has just released which addresses this issue:
https://github.com/TiberiumFusion/FixedSteamFriendsUI/releases/tag/Release-v1.1.0

Please try it out, and let me know if it solves the problem for you.

**Comment by vitalii0133** [comment]
> @vitalii0133 Version 1.1.0 has just released which addresses this issue: https://github.com/TiberiumFusion/FixedSteamFriendsUI/releases/tag/Release-v1.1.0
> 
> Please try it out, and let me know if it solves the problem for you.

Yes, problem solved
