### ISSUE TITLE
Unable to join or watch or ping servers.

### ISSUE THREAD

**Issue by Z4mp1E** [TiberiumFusion/FixedSteamFriendsUI#4]
Unable to Ping any Region" error persists when attempting matchmaking. When selecting "Refresh Pings", client attempts indefinitely to calculate pings dota 2.

![image](https://github.com/TiberiumFusion/FixedSteamFriendsUI/assets/125710651/3c935a87-84f3-4264-a689-7b4491d610c2)

**Comment by TiberiumFusion** [comment]
Not related to the Steam friends/chat PWA. Games do not use the friends/chat PWA.

I have no idea what game that screenshot is from. We have a thread here: https://steamcommunity.com/groups/ClientDowngrades/discussions/0/3881597531957111026/ that is probably what you are looking for.
